export const Images = {
  IMG_SCOOTER: require('../Assets/Image/scooter.png'),
  IMG_HISTORY: require('../Assets/Image/transactionHistory.png'),
  IMG_WALLET: require('../Assets/Image/walletPasses.png'),
  IMG_DINING: require('../Assets/Image/dining.png'),
  IMG_ARROW: require('../Assets/Image/right-arrow.png'),
  IMG_LOCATION: require('../Assets/Image/location.png'),
  IMG_USER: require('../Assets/Image/userIcon.png'),
  IMG_LANGUAGE: require('../Assets/Image/launguageSign.png'),
  IMG_SEARCH_ICON: require('../Assets/Image/searchIcon.png'),
  IMG_MIC: require('../Assets/Image/mic.png'),
  IMG_FILTER: require('../Assets/Image/settings-sliders.png'),
  IMG_DOWN_TRIANGLE_ARROW: require('../Assets/Image/triangle_down.png'),
  IMG_CIRCAL_THALI_MEAL: require('../Assets/Image/circle_shaped_food.png'),
  IMG_FRENCH_FRIES: require('../Assets/Image/french_fries.jpg'),
  IMG_LEAF: require('../Assets/Image/leaf.png'),
  IMG_HEART: require('../Assets/Image/love.png'),
  IMG_STAR: require('../Assets/Image/star.png'),
  IMG_STOPWATCH: require('../Assets/Image/stopwatch.png'),
  IMG_RUPEE: require('../Assets/Image/rupee.png'),
  IMG_DISCOUNT: require('../Assets/Image/discount.png'),
  IMG_TABLE: require('../Assets/Image/table.png')
};
